### ISSUE TITLE
Include calculations output as a pop-up window instead of showing in the console

### ISSUE THREAD

**Issue by toadkarter** [djordje-kalojevic/HSR-Optimal-Rotation-Calculator#1]
Hey there! Toadkarter here, I messaged on Reddit about possibly helping out with this tool :) Nice work, this is definitely going to help a lot of people! 

One possible thing I was thinking that might be cool to add is a little pop-up window that shows the results of the calculations, just so that everything is shown in the GUI instead of having the results be in the CLI. If you think that might be a good idea then I can have a bash at putting something together and submit a pull request! I'm on holidays this week and am away from my PC, but can definitely put something together when I am back!

**Comment by djordje-kalojevic** [comment]
Heyo, hope you have a great holiday!

I've thought about something like that quite early on in development, but decided against it cause I wanted the user to have access to all the previous calculations so they can min-max loadouts a bit more easily. That being said, maybe we could offer it as an option? I've worked quite a lot in pyqt6 so I can quickly make an early version. Question is what would be the best way to present this option to the user.

If you have any ideas, I would always be happy to hear them!^^

**Comment by toadkarter** [comment]
Oh yeah, that's actually a very good point! An option could be good yeah, but I suppose if it's working as intended for the time being then it might make sense to leave it as is :)
