### ISSUE TITLE
AttributeError: 'LightCone' object attribute 'trigger' is read-only

### ISSUE THREAD

**Issue by rasperin** [djordje-kalojevic/HSR-Optimal-Rotation-Calculator#11]
**Describe the bug**
AttributeError: 'LightCone' object attribute 'trigger' is read-only

(Not that slots being a read only issue is a python3.11 thing but I thought I'd come back and edit to mention this is python3.11)

**To Reproduce**
1. Open App
2. Select your character fill out the information
**Actually Relevant Details**
3. Equipment info set Quid Pro Quo (though looking at this error after fixing it locally, it seems like this would happen on any light cone), set Super Imposition to 4 (ditto)
4. Fill the rest of the info out and click Confirm Selection.
5. Application Crashes stack trace (relevant part)
6. HSR-Optimal-Rotation-Calculator/gui_scripts/gui.py", line 181, in _collect_gear_input
    self.user_input.support_light_cone.trigger = self._get_support_lc_triggers()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'LightCone' object attribute 'trigger' is read-only

**Expected behavior**
Not to crash and calculate

**Additional context**
Fixed locally by changing `LightCone.trigger = Counter()` to `trigger: Counter = field(default_factory=Counter) `.

**Comment by djordje-kalojevic** [comment]
Hi rasperin,

Thank you for reaching out and even fixing the issue! Unfortunately, I had to take a break from the project to focus on real life things.

New version should be up tonight or tomorrow, and I have preemptively fixed any other "Counter()" occurrence. However, I will do a once over regarding any other slots in the future. Of course I will credit you with the solution as well.

Thank you once again and sorry for the late response.
